export const SLOTS = [
  "unknown",
  "N/A",
  "used as light",
  "worn on finger",
  "worn around neck",
  "worn on torso",
  "worn on horns",
  "worn on head",
  "worn over eyes",
  "worn on ear",
  "worn on snout",
  "worn on legs",
  "worn on four legs",
  "worn on ankle",
  "worn on feet",
  "worn on hooves",
  "worn on hands",
  "worn on arms",
  "worn as shield",
  "worn about body",
  "worn on waist",
  "worn around wrist",
  "wielded",
  "held",
  "using fishing line",
  "using as bait",
  "using as lure",
  "dual wielded",
  "banner",
  "worn on bosom",
  "trinal wielded",
  "worn inside cover",
];

export default SLOTS;
